CREATE DATABASE Bsc_Hons_376
SELECT * FROM Albums
SELECT * FROM Artists
SELECT * FROM Songs

--Part – A
--1
--Retrieve a unique genre of songs.
SELECT DISTINCT GENRE FROM SONGS

--2
--Find top 2 albums released before 2010.
SELECT TOP 2 ALBUM_ID FROM AlBUMS WHERE Release_year<2010

--3
--Insert Data into the Songs Table. (1245, ‘Zaroor’, 2.55, ‘Feel good’, 1005)
INSERT INTO SONGS VALUES(1245,'ZARROR',2.55,'FEEL GOOD',1005)

--4
--Change the Genre of the song ‘Zaroor’ to ‘Happy’
UPDATE SONGS SET GENRE='HAPPY' WHERE GENRE='ZARROR'

--5
--Delete an Artist ‘Ed Sheeran’
DELETE FROM ARTISTS WHERE ARTIST_NAME='ED SHEERAN'

--6
--Add a New Column for Rating in Songs Table. [Ratings decimal(3,2)]
ALTER TABLE SONGS ADD RATING DECIMAL(3,2)

--7
--Retrieve songs whose title starts with 'S'.
SELECT SONG_TITLE FROM SONGS WHERE SONG_TITLE LIKE 'S%'

--8
--Retrieve all songs whose title contains 'Everybody'.
SELECT SONG_TITLE FROM SONGS WHERE SONG_TITLE LIKE '%EVERYBODY%'

--9
--Display Artist Name in Uppercase.
SELECT UPPER(ARTIST_NAME) FROM ARTISTS

--10
--Find the Square Root of the Duration of a Song ‘Good Luck’
SELECT SQRT(DURATION) FROM SONGS WHERE SONG_TITLE='GOOD LUCK'

--11
--Find Current Date.
SELECT GETDATE()

--12
--Find the number of albums for each artist.
SELECT ARTIST_NAME, COUNT(ALBUM_ID) FROM ALBUMS JOIN ARTISTS ON ALBUMS.ARTIST_ID=ARTISTS.ARTIST_ID GROUP BY ARTIST_NAME

--13
--Retrieve the Album_id which has more than 5 songs in it.
 SELECT SONGS.ALBUM_ID FROM SONGS GROUP BY ALBUM_ID HAVING COUNT(SONG_ID) >5

--14
--Retrieve all songs from the album 'Album1'. (using Subquery)
SELECT SONG_TITLE,DURATION,GENRE FROM SONGS WHERE ALBUM_ID IN(SELECT ALBUM_ID FROM ALBUMS WHERE ALBUM_TITLE='ALBUM1')

--15
--Retrieve all albums name from the artist ‘Aparshakti Khurana’ (using Subquery)
SELECT ALBUM_TITLE FROM ALBUMS WHERE ARTIST_ID IN(SELECT ARTIST_ID FROM ARTISTS WHERE ARTIST_NAME='APARSHAKTI KHURANA')

--16
--Retrieve all the song titles with its album title.
SELECT SONG_TITLE,ALBUM_TITLE FROM SONGS JOIN ALBUMS ON SONGS.ALBUM_ID=ALBUMS.ALBUM_ID

--17
--Find all the songs which are released in 2020.
SELECT SONG_TITLE,RELEASE_YEAR FROM SONGS JOIN ALBUMS ON SONGS.ALBUM_ID=ALBUMS.ALBUM_ID WHERE RELEASE_YEAR=2020

--18
--Create a view called ‘Fav_Songs’ from the songs table having songs with song_id 101-105.
CREATE VIEW FAV_SONGS AS SELECT SONG_ID,SONG_TITLE,DURATION,GENRE,ALBUM_ID FROM SONGS WHERE SONG_ID BETWEEN 101 AND 105 
DROP VIEW FAV_SONGS

--19
--Update a song name to ‘Jannat’ of song having song_id 101 in Fav_Songs view.
UPDATE FAV_SONGS SET SONG_TITLE='JANNAT' WHERE SONG_ID=101
SELECT * FROM FAV_SONGS

--20
--Find all artists who have released an album in 2020.
SELECT DISTINCT ARTIST_NAME FROM ARTISTS JOIN ALBUMS ON ARTISTS.ARTIST_ID=ALBUMS.ARTIST_ID WHERE RELEASE_YEAR=2020

--21
--Retrieve all songs by Shreya Ghoshal and order them by duration
SELECT SONG_ID,SONG_TITLE,DURATION FROM SONGS JOIN ALBUMS ON SONGS.ALBUM_ID=ALBUMS.ALBUM_ID JOIN ARTISTS ON ARTISTS.ARTIST_ID=ALBUMS.ARTIST_ID WHERE ARTIST_NAME='SHREYA GHOSHAL' ORDER BY DURATION 

--Part – B
--22
--Retrieve all song titles by artists who have more than one album.
SELECT SONG_TITLE FROM SONGS JOIN ALBUMS ON SONGS.ALBUM_ID=ALBUMS.ALBUM_ID JOIN ARTISTS ON ARTISTS.ARTIST_ID=ALBUMS.ARTIST_ID WHERE ARTISTS.ARTIST_ID IN(SELECT ARTIST_ID FROM ALBUMS GROUP BY ARTIST_ID HAVING COUNT(ALBUM_ID)>1)

--23
--Retrieve all albums along with the total number of songs.
SELECT ALBUM_TITLE,COUNT(SONG_ID) FROM ALBUMS LEFT JOIN SONGS ON ALBUMS.ALBUM_ID=SONGS.ALBUM_ID GROUP BY ALBUM_TITLE

--24
--Retrieve all songs and release year and sort them by release year.
SELECT SONG_TITLE,DURATION,GENRE,RELEASE_YEAR FROM SONGS LEFT JOIN ALBUMS ON SONGS.ALBUM_ID=ALBUMS.ALBUM_ID ORDER BY RELEASE_YEAR

--25
--Retrieve the total number of songs for each genre, showing genres that have more than 2 songs.
SELECT COUNT(SONG_ID),GENRE FROM SONGS GROUP BY GENRE HAVING COUNT(SONG_ID)>2

--26--List all artists who have albums that contain more than 3 songs.SELECT ARTISTS.ARTIST_ID,ARTISTS.ARTIST_NAME,COUNT(SONG_ID) FROM ARTISTS  JOIN ALBUMS ON ARTISTS.ARTIST_ID=ALBUMS.ARTIST_ID JOIN SONGS ON ALBUMS.ALBUM_ID=SONGS.ALBUM_ID GROUP BY ARTISTS.ARTIST_ID,ARTISTS.ARTIST_NAME HAVING COUNT(SONG_ID)>3--Part – C
--27
--Retrieve albums that have been released in the same year as 'Album4'
SELECT ALBUM_TITLE,RELEASE_YEAR FROM ALBUMS WHERE RELEASE_YEAR IN(SELECT RELEASE_YEAR FROM ALBUMS WHERE ALBUM_TITLE='ALBUM4')

--28
--Find the longest song in each genre
SELECT GENRE FROM SONGS WHERE DURATION=(SELECT MAX(DURATION) FROM SONGS)GROUP BY GENRE

--29
--Retrieve the titles of songs released in albums that contain the word 'Album' in the title.
SELECT SONG_TITLE FROM SONGS JOIN ALBUMS ON SONGS.ALBUM_ID=ALBUMS.ALBUM_ID WHERE ALBUMS.ALBUM_TITLE LIKE'%ALBUM%'

--30--Retrieve the total duration of songs by each artist where total duration exceeds 15 minutes.SELECT SUM(DURATION),ARTIST_NAME,ARTISTS.ARTIST_ID FROM ALBUMS JOIN SONGS ON ALBUMS.ALBUM_ID=SONGS.ALBUM_ID JOIN ARTISTS ON ARTISTS.ARTIST_ID=ALBUMS.ARTIST_ID GROUP BY ARTISTS.ARTIST_ID,ARTIST_NAME HAVING SUM(DURATION)>15 
